### request an order
POST {{host}}/order/request
Content-Type: application/json

{
  "customerName": "elijahmutune",
  "items": [
    {
      "itemName": "spoon",
      "itemCount": 20
    },
    {
      "itemName": "plate",
      "itemCount": 20
    }, {
      "itemName": "knife",
      "itemCount": 10
    }
  ]
}

### add an order
POST {{host}}/order/add
Content-Type: application/json

{
  "orderId": 3,
  "payment": {
    "paymentType": "bank payment",
    "bankName": "equity",
    "accountName": "kamarbaraka",
    "mobileNumber": "0706354825"
  }
}

### dispatch order
POST {{host}}/order/dispatch
Content-Type: application/json

{
  "orderIds": [
    52
  ],
  "usernameOfDispatcher": "kamarbaraka",
  "dispatchLocation": "thika"
}

### receive an order
POST {{host}}/order/receive
Content-Type: application/json

{
  "batchId": 3,
  "recipient": "kamarbaraka",
  "location": "nairobi"
}

### complete an order
POST {{host}}/order/complete
Content-Type: application/json

{
  "orderId": 1,
  "signer": "elijahmutune",
  "location": "nairobi"
}