### stock add
POST {{host}}/stock/add
Content-Type: application/json

{
  "location": {
    "isle": 5,
    "section": "secA"
  },
  "name": "glass",
  "code": "1425145786",
  "price": 85.0,
  "count": 25
}

### delete stock
DELETE {{host}}/stock/delete/spoon
Content-Type: application/json

### update stock
PUT {{host}}/stock/update
Content-Type: application/json

{
  "itemName": "sufuria",
  "itemCode": "123456987",
  "price": 600.0,
  "count": 45,
  "location": {
    "section": "sec3",
    "isle": 4
  }
}

### get stock
GET {{host}}/stock/fetch?item_name=sufuria
Content-Type: application/json