### stock add
POST {{host}}/stock/add
Content-Type: application/json

{
  "location": {
    "isle": 1,
    "section": "secA"
  },
  "name": "spoon",
  "code": "124548969",
  "price": 15.0,
  "count": 45
}

### delete stock
DELETE {{host}}/stock/delete/spoon
Content-Type: application/json

### update stock
PUT {{host}}/stock/update
Content-Type: application/json

{
  "itemName": "sufuria",
  "itemCode": "123456987",
  "price": 600.0,
  "count": 45,
  "location": {
    "section": "sec3",
    "isle": 4
  }
}