#### user registration
POST {{host}}/user/register
Content-Type: application/json

{
  "username": "murungaevans",
  "firstName": "evans",
  "lastName": "murunga",
  "role": "CUSTOMER",
  "contact": "07556925",
  "address": {
    "street": "piloti",
    "city": "Thika",
    "country": "Kenya",
    "zipcode": "456328"
  },
  "password": "123456",
  "profilePicture": [
    ""
  ]
}

### user login
POST {{host}}/user/login
Content-Type: application/json

{
  "username": "mimiwat",
  "password": "123456"
}

### user fetch
GET {{host}}/user/fetch?username=kamar254baraka@gmail.com
Content-Type: application/json

### update user
PUT {{host}}/user/update
Content-Type: application/json

{
  "username": "kamarbaraka",
  "password": "123456",
  "user": {
  "username": "kimonje",
  "firstName": "kamar",
  "lastName": "baraka",
  "role": {
    "roleName": "ADMIN",
    "roleDescription": "system admin"
  },
  "address": {
    "street": "piloti",
    "city": "Thika",
    "country": "Uganda",
    "zipcode": "456328"
  },
  "password": "123456",
  "profilePicture": [
    ""
  ]
}
}

### delete user
DELETE {{host}}/user/delete
Content-Type: application/json

{
  "username": "samonte",
  "password": "123456"
}

### get all users
GET {{host}}/user/fetch?username=mimiwathua
Content-Type: application/json
Cookie: JSESSIONID=17B92DED8E23925876ED55234C0788D0

### get all stock
GET {{host}}/stock
Content-Type: application/json

### add stock
POST {{host}}/stock/add
Content-Type: application/json

{
  "itemName": "spoon",
  "itemCode": "123845679514",
  "price": 23.0,
  "location": {
    "section": "secA",
    "isle": 3
  }
}